# Generated by Django 5.2.6 on 2025-09-20 01:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=50)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel')], max_length=10)),
                ('filters', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'data_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregatedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_trips', models.IntegerField(default=0)),
                ('total_distance', models.FloatField(default=0)),
                ('mode_breakdown', models.JSONField(default=dict)),
                ('purpose_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aggregated_stats',
                'unique_together': {('date',)},
            },
        ),
    ]
